# Use the official OpenJDK image
FROM openjdk:21-jdk

# Install Python
RUN microdnf update && \
    microdnf install -y python3 && \
    microdnf install -y nodejs && \
    microdnf clean all

# Make python3 default
RUN ln -s /usr/bin/python3 /usr/bin/python
