#!/usr/bin/env python3

import subprocess
import sys
import os

url = 'https://codeberg.org/paintgoblin/shugits/raw/commit/cadecff37713c5883d4a203f5063d54ffb3198c2/sbt-launch.jar'
destination = 'target/sbt-launch.jar'

def main():
    os.makedirs(os.path.dirname(destination), exist_ok=True)

    if not os.path.isfile(destination):
        download_file(url, destination)

    exit(
        subprocess.run(['java', '-jar', destination] + sys.argv[1:], check=False).returncode
    )

def download_file(url, destination):
    import sys
    if sys.version_info[0] < 3:
        import urllib2  # Python 2.7
        urlopen = urllib2.urlopen
    else:
        import urllib.request as urllib_request  # Python 3.x
        urlopen = urllib_request.urlopen
    response = urlopen(url)
    with open(destination, 'wb') as f:
        f.write(response.read())

if __name__ == '__main__':
    main()
