name: build this sbt module
on:
  push:
    branches:
      - "*"
jobs:
  build:
    container:
      image: node:16
    runs-on: sam1
    steps:
      - name: setup sbt et al
        run: |
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
          apt-get update
          apt-get install sbt
          apt install -y openjdk-11-jdk sbt
          apt clean
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up GitHub remote with PAT
        env:
          GITHUB_PAT: ${{ secrets.PUBACC }}
          GITHUB_PUB: ${{ secrets.GH_PUB }}
        run: |
          git remote add github "https://${GITHUB_PAT}@github.com/${GITHUB_PUB}.git"
          git remote -v  # Verify remote setup
      - name: build
        run: |
          sbt compile
      - name: test
        run: |
          sbt test
      - name: Force Push to GitHub
        if: ${{ github.ref_name == 'default' }}  # Ensures it only runs on ci2 branch
        run: |
          git push github default --force
          # git push github HEAD:default --force